Add documentation on static asset caching
serverless/cloud pull request #64
Opened 2021-12-08 20:56 UTC by rschick

Let me know if this is too simple and I should add more detail about the `X-Cache-Control` header, etc.

2021-12-17 13:15 UTC, jeremydaly commented
I agree, let’s explain what’s different about the environments. The idea that we automatically handle this for you is another one of those tiny wins that developers don’t think about, then hits them in the face. Don’t be afraid to sell it!

2021-12-17 15:30 UTC, rschick commented
Added more details, let me know what you think!

2021-12-17 15:33 UTC, jeremydaly requested changes

2021-12-17 15:33 UTC, jeremydaly commented on docs/apps/static-assets.md
> +In stage instances static assets are cached in the CDN for up to 24 hours. Responses will include a `Cache-Control` header that tells the CDN to cache the asset for 24 hours, and tells the browser to
Need a comma after instances.

2021-12-17 15:33 UTC, jeremydaly commented on docs/apps/static-assets.md
> +In stage instances static assets are cached in the CDN for up to 24 hours. Responses will include a `Cache-Control` header that tells the CDN to cache the asset for 24 hours, and tells the browser to
And "used _in_ stage instances" at the end of this paragraph

2021-12-23 20:34 UTC, emrahssamdan commented
Let's merge this? @rschick @jeremydaly

2022-01-12 16:12 UTC, merged